services:
  - type: web
    name: crbot
    env: python
    pythonVersion: "3.11.7"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
